environment     =  "dev"
project         =  "mld"
location        = "germanywestcentral"
location_abbrv  =  "gwc"
dbx_account_id  =  "cb698c13-7bf7-4aef-9e1d-78c66a16b17b"
developer_group = "gwc_developers"
admin_group     = "gwc_metastore_admins"