name: "Create state storage"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
      project:
        description: 'Project to deploy to'
        required: true
        default: 'ml'

permissions:
    id-token: write
    contents: read

jobs:

    deploy:
        environment: dev
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1
              with:
                client-id: ${{ vars.AZURE_CLIENT_ID }}
                tenant-id: ${{ vars.AZURE_TENANT_ID }}
                subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

            - name: Run az commands
              run: |
                scripts/create_state_storage.ps1 
                -SubscriptionId "${{ vars.AZURE_SUBSCRIPTION_ID }}" \
                -Environment "${{ inputs.environment }}" \
                -Location "germanywestcentral" \
                -LocationAbbrv "gwc" \
                -Project "${{ inputs.project }}"