name: Deploy Azure Infra
on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  plan:
    runs-on: 'ubuntu-latest'
    steps:
        - name: Plan
          uses: ./.github/actions/run-terraform/
          with:   
            stack: azure
            command: plan
            runs-on: ubuntu-latest
            flags: ""
            environment: dev
            state_storage: ${{ vars.STATE_STORAGE_NAME }}
            state_resource_group: ${{ vars.STATE_STORAGE_RG_NAME }}
            azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
            azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
            azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}