name: Deploy Databricks Account Configuration
on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  plan:
    environment: dev
    runs-on: 'ubuntu-latest'
    steps:
        - uses: actions/checkout@v4
          with:
            lfs: true
        - name: Plan
          uses: ./.github/actions/run-terraform/
          with:   
            stack: account
            command: plan
            flags: ""
            environment: dev
            state_storage: ${{ vars.STATE_STORAGE_NAME }}
            state_resource_group: ${{ vars.STATE_STORAGE_RG_NAME }}
            azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
            azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
            azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            azure_principal_id: ${{ vars.AZURE_PRINCIPAL_ID }}
  apply:
    environment: dev
    runs-on: 'ubuntu-latest'
    needs: plan
    steps:
        - uses: actions/checkout@v4
          with:
            lfs: true
        - name: Apply
          uses: ./.github/actions/run-terraform/
          with:   
            stack: account
            command: apply
            flags: "--auto-approve"
            environment: dev
            state_storage: ${{ vars.STATE_STORAGE_NAME }}
            state_resource_group: ${{ vars.STATE_STORAGE_RG_NAME }}
            azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
            azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
            azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
            azure_principal_id: ${{ vars.AZURE_PRINCIPAL_ID }}